name: Update Flight Forecast

on:
  schedule:
    - cron: '0 20 * * *'  # 每天凌晨執行
  workflow_dispatch:      # 允許手動觸發

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create data directory
        run: mkdir -p public/data
      
      - name: Download forecast
        env:
          TZ: 'Asia/Taipei'  # 設置時區為台北時間
        run: |
          DATE=$(date +%Y_%m_%d)
          TOMORROW=$(date -d "tomorrow" +%Y_%m_%d)
          
          # 下載今天的數據
          curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" \
               -H "Referer: https://www.taoyuan-airport.com" \
               -o public/data/$DATE.xls \
               https://www.taoyuan-airport.com/uploads/fos/$DATE.xls
          
          # 下載明天的數據
          curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" \
               -H "Referer: https://www.taoyuan-airport.com" \
               -o public/data/$TOMORROW.xls \
               https://www.taoyuan-airport.com/uploads/fos/$TOMORROW.xls
          
      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add public/data
          git commit -m "Update forecast data for $(TZ='Asia/Taipei' date +%Y-%m-%d)" || exit 0
          git push 