name: Update Flight Forecast

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨執行
  workflow_dispatch:      # 允許手動觸發

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Download forecast
        run: |
          mkdir -p public/data
          DATE=$(date +%Y_%m_%d)
          TOMORROW=$(date -d "tomorrow" +%Y_%m_%d)
          curl -L -o "public/data/${DATE}.xls" "https://www.taoyuan-airport.com/uploads/fos/${DATE}.xls"
          curl -L -o "public/data/${TOMORROW}.xls" "https://www.taoyuan-airport.com/uploads/fos/${TOMORROW}.xls"
          
      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add public/data
          git commit -m "Update forecast data for $(date +%Y-%m-%d)" || exit 0
          git push